# Generated by Django 5.1.15 on 2026-09-15 20:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0006_testattempt_state_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Body')),
                ('notification_type', models.CharField(choices=[('NOTICE', 'Notice'), ('REMINDER', 'Reminder'), ('ANNOUNCEMENT', 'Announcement'), ('ALERT', 'Alert')], db_index=True, default='NOTICE', max_length=32, verbose_name='Category')),
                ('audience', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('ALL_STUDENTS', 'All Students')], db_index=True, default='INDIVIDUAL', max_length=32, verbose_name='Target Audience')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='assessments.assessment', verbose_name='Associated Assessment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient User')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender Admin')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='core_notifi_recipie_1d5476_idx'), models.Index(fields=['notification_type', '-created_at'], name='core_notifi_notific_38b6f7_idx')],
            },
        ),
    ]
