# Generated by Django 5.1.15 on 2026-09-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proctoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proctoringevent',
            name='is_confirmed',
            field=models.BooleanField(db_index=True, default=True, help_text='True if event is an authoritative confirmed disciplinary violation, False for raw detection hints.'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['session', 'is_confirmed'], name='idx_event_session_confirmed'),
        ),
    ]
