# Generated by Django 5.1.15 on 2026-09-10 13:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_testattempt_state_version'),
        ('proctoring', '0002_proctoringevent_is_confirmed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityIncident',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_incident_id', models.UUIDField(db_index=True)),
                ('incident_type', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('server_received_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrity_incidents', to='assessments.testattempt')),
            ],
            options={
                'db_table': 'proctoring_integrity_incidents',
                'indexes': [models.Index(fields=['attempt', 'client_incident_id'], name='idx_incid_att_client_id')],
                'constraints': [models.UniqueConstraint(fields=('attempt', 'client_incident_id'), name='unique_attempt_client_incident')],
            },
        ),
    ]
