# Generated by Django 5.1.15 on 2026-09-12 19:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_testattempt_state_version'),
        ('invigilation', '0003_alter_proctorintervention_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctorintervention',
            name='event_type',
            field=models.CharField(choices=[('WARNING_ISSUED', 'Warning Issued'), ('WARNING_ACKNOWLEDGED', 'Warning Acknowledged'), ('PAUSE_STARTED', 'Pause Started'), ('PAUSE_ENDED', 'Pause Ended'), ('ROOM_SCAN_REQUESTED', 'Room Scan Requested'), ('ROOM_SCAN_COMPLETED', 'Room Scan Completed'), ('TERMINATION_REQUESTED', 'Termination Requested'), ('TERMINATION_CONFIRMED', 'Termination Confirmed'), ('TERMINATION_PENDING', 'Termination Pending'), ('TERMINATION_CANCELLED', 'Termination Cancelled'), ('REATTEMPT_AUTHORIZED', 'Reattempt Authorized')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='ProctorReattemptAuthorization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('ACCIDENTAL_VIOLATION', 'Accidental Violation'), ('TECHNICAL_PROBLEM', 'Technical Problem'), ('PROCTOR_DECISION', 'Proctor Decision'), ('OTHER', 'Other')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CONSUMED', 'Consumed')], db_index=True, default='AUTHORIZED', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reattempt_authorizations', to='assessments.assessment')),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_reattempts', to=settings.AUTH_USER_MODEL)),
                ('new_attempt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reattempt_origin', to='assessments.testattempt')),
                ('original_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reattempt_authorizations', to='assessments.testattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reattempt_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctor_reattempt_authorizations',
                'constraints': [models.UniqueConstraint(fields=('student', 'assessment'), name='unique_reattempt_per_student_assessment'), models.UniqueConstraint(fields=('original_attempt',), name='unique_reattempt_per_original_attempt')],
            },
        ),
    ]
