# Generated by Django 5.1.15 on 2026-09-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_user_unique_admin_id_for_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='certificate_name',
            field=models.CharField(blank=True, default='', help_text='Canonical student full name printed on Craft Society participation certificates.', max_length=255, verbose_name='Full Name for Certificate Printing'),
        ),
    ]
