# Generated by Django 5.1.15 on 2026-09-07 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_studentprofile_certificate_name'),
        ('assessments', '0003_assessment_target_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='camera_required',
            field=models.BooleanField(default=True, help_text='Requires student webcam access and pre-exam face verification.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='face_detection_enabled',
            field=models.BooleanField(default=True, help_text='Monitors face presence and candidate visibility.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='gaze_detection_enabled',
            field=models.BooleanField(default=True, help_text='Tracks eye gaze deviation away from the examination viewport.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='head_movement_detection_enabled',
            field=models.BooleanField(default=True, help_text='Tracks persistent head turns or looking away.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='max_confirmed_violations',
            field=models.PositiveIntegerField(default=3, help_text='Minimum confirmed violation threshold is strictly 3.', validators=[django.core.validators.MinValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='assessment',
            name='multiple_face_detection_enabled',
            field=models.BooleanField(default=True, help_text='Detects multiple individuals in the camera frame.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='phone_detection_enabled',
            field=models.BooleanField(default=True, help_text='Detects unauthorized mobile phones or devices via vision model.'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='proctoring_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for AI-assisted proctoring and secure browser mode.'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='disqualification_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='disqualified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='is_disqualified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='target_sections',
            field=models.ManyToManyField(blank=True, help_text='Academic sections targeted for this assessment (deprecated for active workflows; preserved for historical records).', related_name='targeted_assessments', to='accounts.section'),
        ),
    ]
