# Generated by Django 5.1.15 on 2026-09-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_testattempt_termination_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testattempt',
            name='state_version',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
